name: Docker Image CI

on:
  push:
    branches: [ master ]
  schedule:
    - cron: 0 0 1 * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push debian image
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            shockpast/garrysmod:debian
            shockpast/garrysmod:latest
          file: debian.Dockerfile

      # - name: Push debian-x64 image
      #   if: ${{ github.event_name != 'workflow_dispatch' }}
      #   uses: docker/build-push-action@v6
      #   with:
      #     push: true
      #     tags: shockpast/garrysmod:debian-x64-root
      #     file: debian-x64-root.Dockerfile

      - name: Push ubuntu image
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: shockpast/garrysmod:ubuntu
          file: ubuntu.Dockerfile